AllCops:
    SuggestExtensions: false
    NewCops: enable

Metrics/CyclomaticComplexity:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

Metrics/PerceivedComplexity:
    Enabled: false

Layout/LineLength:
    Enabled: false

Metrics/BlockLength:
    Enabled: false

Style/Documentation:
    Enabled: false

Metrics/AbcSize:
    Enabled: false